CREATE TABLE ROLE(
	ID INT NOT NULL PRIMARY KEY
	, NAME VARCHAR(20) NOT NULL
);

CREATE TABLE USER (
	ID LONG NOT NULL AUTO_INCREMENT PRIMARY KEY
	, ROLE_ID INT NOT NULL
	, USERNAME VARCHAR(25) NOT NULL UNIQUE
	, PASSWORD VARCHAR(250) NOT NULL
	, ACTIVE TINYINT NOT NULL
	, CREATION TIMESTAMP NOT NULL
	, UPDATED_BY LONG NOT NULL
	, UPDATED_ON TIMESTAMP NOT NULL
);

CREATE TABLE TODO (
	  ID LONG NOT NULL AUTO_INCREMENT PRIMARY KEY
	, USER_ID LONG NOT NULL
    , TITLE VARCHAR(150) NOT NULL
    , DESCRIPTION VARCHAR(450) NOT NULL
    , CREATION TIMESTAMP NOT NULL
    , ESTIMATED_COMPLETION TIMESTAMP NOT NULL
    , COMPLETED TINYINT /* YES/NO*/
    , STATUS VARCHAR(7) /*(ON_TIME, LATE)*/
    , DELETED TINYINT NOT NULL
    , UPDATED_BY LONG NOT NULL
    , UPDATED_ON TIMESTAMP NOT NULL
);
